CREATE TABLE ACTOR
(
AID INT NOT NULL,
NAME VARCHAR(20),
OSCARS INT NOT NULL,
AGE INT NOT NULL,
PIRMARY KEY (AID)
);

CREATE TABLE DIRECTOR
(
  DID INT NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  NUM_DIRECTED INT NOT NULL,
  OSCARS INT NOT NULL,
  PRIMARY KEY (DID)
);

CREATE TABLE DISTRIBUTOR
(
  DISID INT NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  CITY VARCHAR(15) NOT NULL,
  REVENUE_YTD DECIMAL(10,2)
  PRIMARY KEY (DISID) 

);
CREATE TABLE GENRE
(
  GID INT NOT NULL,
  TITLE VARCHAR(20),
  PRIMARY KEY (GID)
);

CREATE TABLE MOVIE
(
  ID INT NOT NULL,
  TITLE VARCHAR(50),
  REVENUE DECIMAL(10,2),
  YEAR INT NOT NULL,
  OSCARS INT NOT NULL,
  DID INT NOT NULL,
  DISID INT NOT NULL,
  GID INT NOT NULL,
  SID INT NOT NULL,
  FOREIGN KEY (DID) REFERENCES DIRECTOR(DID),
  FOREIGN KEY (DISID) REFERENCES DISTRIBUTOR(DISID), 
  FOREIGN KEY (GID) REFERENCES GENRE(GID),
  FOREIGN KEY (SID) REFERENCES STUDIO(SID)
);

CREATE TABLE STUDIO
(
  SID INT NOT NULL,
  NAME VARCHAR(20),
  CITY VARCHAR(15),
  REVENUE_YTD DECIMAL(10,2)
);
